psql --host=database-2.czezomqwfxmw.us-east-1.rds.amazonaws.com --port=5432 --username=postgres --password=095126167170 --dbname=FinalProject
delete from br_videoinfos;
delete from br_videotrendings;
delete from ca_videoinfos;
delete from ca_videotrendings;
delete from de_videoinfos;
delete from de_videotrendings;
delete from fr_videoinfos;
delete from fr_videotrendings;
delete from kr_videoinfos;
delete from kr_videotrendings;
delete from mx_videoinfos;
delete from mx_videotrendings;
delete from ru_videoinfos;
delete from ru_videotrendings;
delete from gb_videoinfos;
delete from gb_videotrendings;
delete from in_videoinfos;
delete from in_videotrendings;
delete from jp_videoinfos;
delete from jp_videotrendings;
\copy br_videoinfos from 'C:\Users\user\projects\br_videoinfo.csv' WITH (FORMAT csv,ENCODING 'UTF-8');
\copy br_videotrendings from 'C:\Users\user\projects\br_videotrending.csv' WITH (FORMAT csv,ENCODING 'UTF-8');
\copy ca_videoinfos from 'C:\Users\user\projects\ca_videoinfo.csv' WITH (FORMAT csv,ENCODING 'UTF-8');
\copy ca_videotrendings from 'C:\Users\user\projects\ca_videotrending.csv' WITH (FORMAT csv,ENCODING 'UTF-8');
\copy de_videoinfos from 'C:\Users\user\projects\de_videoinfo.csv' WITH (FORMAT csv,ENCODING 'UTF-8');
\copy de_videotrendings from 'C:\Users\user\projects\de_videotrending.csv' WITH (FORMAT csv,ENCODING 'UTF-8');
\copy fr_videoinfos from 'C:\Users\user\projects\fr_videoinfo.csv' WITH (FORMAT csv,ENCODING 'UTF-8');
\copy fr_videotrendings from 'C:\Users\user\projects\fr_videotrending.csv' WITH (FORMAT csv,ENCODING 'UTF-8');
\copy gb_videoinfos from 'C:\Users\user\projects\gb_videoinfo.csv' WITH (FORMAT csv,ENCODING 'UTF-8');
\copy gb_videotrendings from 'C:\Users\user\projects\gb_videotrending.csv' WITH (FORMAT csv,ENCODING 'UTF-8');
\copy in_videoinfos from 'C:\Users\user\projects\in_videoinfo.csv' WITH (FORMAT csv,ENCODING 'UTF-8');
\copy in_videotrendings from 'C:\Users\user\projects\in_videotrending.csv' WITH (FORMAT csv,ENCODING 'UTF-8');
\copy jp_videoinfos from 'C:\Users\user\projects\jp_videoinfo.csv' WITH (FORMAT csv,ENCODING 'UTF-8');
\copy jp_videotrendings from 'C:\Users\user\projects\jp_videotrending.csv' WITH (FORMAT csv,ENCODING 'UTF-8');
\copy kr_videoinfos from 'C:\Users\user\projects\kr_videoinfo.csv' WITH (FORMAT csv,ENCODING 'UTF-8');
\copy kr_videotrendings from 'C:\Users\user\projects\kr_videotrending.csv' WITH (FORMAT csv,ENCODING 'UTF-8');
\copy mx_videoinfos from 'C:\Users\user\projects\mx_videoinfo.csv' WITH (FORMAT csv,ENCODING 'UTF-8');
\copy mx_videotrendings from 'C:\Users\user\projects\mx_videotrending.csv' WITH (FORMAT csv,ENCODING 'UTF-8');
\copy ru_videoinfos from 'C:\Users\user\projects\ru_videoinfo.csv' WITH (FORMAT csv,ENCODING 'UTF-8');
\copy ru_videotrendings from 'C:\Users\user\projects\ru_videotrending.csv' WITH (FORMAT csv,ENCODING 'UTF-8');

